<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Orders_nav-cart-icon nav-sprite</name>
   <tag></tag>
   <elementGuidId>e091585f-2a83-4cfe-a342-0e8c5fb8eca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nav-cart-icon.nav-sprite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-cart-count-container']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7398014-8ce7-407e-8372-4050f790d593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-cart-icon nav-sprite</value>
      <webElementGuid>236710ba-67d8-49b1-9aff-724ffc22ef85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-cart-count-container&quot;)/span[@class=&quot;nav-cart-icon nav-sprite&quot;]</value>
      <webElementGuid>8f5540aa-6f23-4e7d-9cb4-f93f204ea702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-cart-count-container']/span[2]</value>
      <webElementGuid>ecf630d1-5aef-4aa1-8470-5b2c342d7e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div/span[2]</value>
      <webElementGuid>6cfe7425-4660-47e5-872f-c4d5010db039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
