<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Autofill</name>
   <tag></tag>
   <elementGuidId>eafa6e5e-57f1-4412-ac74-fbe365d0a29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='address-ui-widgets-DetectLocationButton-announce']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.address-ui-widgets-desktop-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3fd0377-40b0-4b1d-abbf-f2eb966452b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address-ui-widgets-desktop-button-text</value>
      <webElementGuid>b47781f3-3b56-4086-866d-315e9f906a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Autofill</value>
      <webElementGuid>e9736a0d-ce3a-48b6-8846-7c9cae9f1eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-DetectLocationButton-announce&quot;)/div[@class=&quot;a-section a-text-center address-ui-widgets-desktop-button-text&quot;]/span[@class=&quot;address-ui-widgets-desktop-button-text&quot;]</value>
      <webElementGuid>24740283-185f-475a-aa23-d0b6c3bf6add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='address-ui-widgets-DetectLocationButton-announce']/div/span</value>
      <webElementGuid>dfe4d21c-6235-4a5b-b64d-482dd7c47095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save time. Autofill your current location.'])[1]/following::span[3]</value>
      <webElementGuid>813436dc-5546-4762-b3de-ac627f900876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a new address'])[1]/following::span[4]</value>
      <webElementGuid>fd7893a3-8f7d-46dd-89b0-78ce6f9ea106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hmm. We could not find your device’s location. Please enter the address manually.'])[1]/preceding::span[1]</value>
      <webElementGuid>4f2a55c8-9c3f-47a3-8701-dc2ee339162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country/Region'])[1]/preceding::span[14]</value>
      <webElementGuid>5c824e28-0fa8-45ac-8ae3-5609e528bc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Autofill']/parent::*</value>
      <webElementGuid>e11fc4e1-f355-4e02-8198-5d5fd31b80b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/span</value>
      <webElementGuid>5e6c139e-9bfa-4c45-b4a8-b8e8552efd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Autofill' or . = 'Autofill')]</value>
      <webElementGuid>7ce4b027-c72f-4fee-a28e-3ee7eb91d4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
